### ISSUE TITLE
Compile failure on PopOS 20.04

### ISSUE THREAD

**Issue by DASPRiD** [alexrsagen/rs-nfc1-sys#2]
When trying to build the `nfc1` sample, `ld` fails with the following errors:

```
  = note: /usr/bin/ld: ./target/debug/build/nfc1-sys-0ec79a32fca2eaef/out/build/libnfc/libnfc.so: undefined reference to `udev_device_get_sysname'
          /usr/bin/ld: ./target/debug/build/nfc1-sys-0ec79a32fca2eaef/out/build/libnfc/libnfc.so: undefined reference to `udev_enumerate_add_match_property'
          /usr/bin/ld: ./target/debug/build/nfc1-sys-0ec79a32fca2eaef/out/build/libnfc/libnfc.so: undefined reference to `udev_enumerate_new'
          /usr/bin/ld: ./target/debug/build/nfc1-sys-0ec79a32fca2eaef/out/build/libnfc/libnfc.so: undefined reference to `udev_enumerate_add_match_subsystem'
          /usr/bin/ld: ./target/debug/build/nfc1-sys-0ec79a32fca2eaef/out/build/libnfc/libnfc.so: undefined reference to `udev_monitor_enable_receiving'
          /usr/bin/ld: ./target/debug/build/nfc1-sys-0ec79a32fca2eaef/out/build/libnfc/libnfc.so: undefined reference to `udev_list_entry_get_next'
          /usr/bin/ld: ./target/debug/build/nfc1-sys-0ec79a32fca2eaef/out/build/libnfc/libnfc.so: undefined reference to `udev_device_new_from_syspath'
          /usr/bin/ld: ./target/debug/build/nfc1-sys-0ec79a32fca2eaef/out/build/libnfc/libnfc.so: undefined reference to `udev_list_entry_get_name'
          /usr/bin/ld: ./target/debug/build/nfc1-sys-0ec79a32fca2eaef/out/build/libnfc/libnfc.so: undefined reference to `udev_monitor_get_fd'
          /usr/bin/ld: ./target/debug/build/nfc1-sys-0ec79a32fca2eaef/out/build/libnfc/libnfc.so: undefined reference to `udev_monitor_receive_device'
          /usr/bin/ld: ./target/debug/build/nfc1-sys-0ec79a32fca2eaef/out/build/libnfc/libnfc.so: undefined reference to `udev_monitor_filter_add_match_subsystem_devtype'
          /usr/bin/ld: ./target/debug/build/nfc1-sys-0ec79a32fca2eaef/out/build/libnfc/libnfc.so: undefined reference to `udev_device_unref'
          /usr/bin/ld: ./target/debug/build/nfc1-sys-0ec79a32fca2eaef/out/build/libnfc/libnfc.so: undefined reference to `udev_device_get_devnode'
          /usr/bin/ld: ./target/debug/build/nfc1-sys-0ec79a32fca2eaef/out/build/libnfc/libnfc.so: undefined reference to `udev_monitor_unref'
          /usr/bin/ld: ./target/debug/build/nfc1-sys-0ec79a32fca2eaef/out/build/libnfc/libnfc.so: undefined reference to `udev_monitor_new_from_netlink'
          /usr/bin/ld: ./target/debug/build/nfc1-sys-0ec79a32fca2eaef/out/build/libnfc/libnfc.so: undefined reference to `udev_device_get_action'
          /usr/bin/ld: ./target/debug/build/nfc1-sys-0ec79a32fca2eaef/out/build/libnfc/libnfc.so: undefined reference to `udev_new'
          /usr/bin/ld: ./target/debug/build/nfc1-sys-0ec79a32fca2eaef/out/build/libnfc/libnfc.so: undefined reference to `udev_enumerate_unref'
          /usr/bin/ld: ./target/debug/build/nfc1-sys-0ec79a32fca2eaef/out/build/libnfc/libnfc.so: undefined reference to `udev_enumerate_scan_devices'
          /usr/bin/ld: ./target/debug/build/nfc1-sys-0ec79a32fca2eaef/out/build/libnfc/libnfc.so: undefined reference to `udev_unref'
          /usr/bin/ld: ./target/debug/build/nfc1-sys-0ec79a32fca2eaef/out/build/libnfc/libnfc.so: undefined reference to `udev_enumerate_get_list_entry'
          collect2: error: ld returned 1 exit status
```

Running on PopOS 20.04 (64 bit) with latest rust version.

**Comment by alexrsagen** [comment]
Hi @DASPRiD, it looks like you are missing the `libudev-dev` package.

Can you try installing it, then try again? 😄

**Comment by DASPRiD** [comment]
Nope, that's already installed:

```
❯ aptitude search libudev-dev
i A libudev-dev                                               - libudev development files
```

**Comment by alexrsagen** [comment]
Okay, i think alexrsagen/rs-usb-compat-01-sys may not be detecting or linking `libudev-dev` correctly on your system, then.

I will download PopOS and debug the issue a bit later. Feel free to try to do so yourself while you await my fix, if you are comfortable editing `build.rs` files responsible for compiling C code.

**Comment by alexrsagen** [comment]
Please note that the code is currently only tested on Windows systems.

The only change needed might be adding `-ludev` to the linker options, when building on Linux systems 🙂

**Comment by alexrsagen** [comment]
Haha yeah I can see why that would be the case 😉

**Comment by siketyan** [comment]
I confirmed the code snippet below works on Ubuntu 21.10 :)

**.cargo/config.toml**
```toml
[build]
rustflags = ["-C", "link-args=-ludev"]
```

**Comment by alexrsagen** [comment]
@DASPRiD Please re-open the issue if this does not work for you.

Tested OK on a clean install of Pop_OS! 20.04, with the following packages installed:
- cargo
- rustc
- clang
- libclang-dev
- cmake
- libudev-dev
